# Generated by Django 2.2.6 on 2019-11-13 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20191110_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='status',
            field=models.CharField(choices=[('AV', 'Dostępna'), ('LO', 'Wypożyczona')], default='AV', max_length=20),
        ),
    ]
