# Generated by Django 2.2.6 on 2019-11-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20191113_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.CharField(max_length=200, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='books',
            name='status',
            field=models.CharField(choices=[('AV', 'Dostępna'), ('LO', 'Wypożyczona')], default='AV', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='books',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Tytuł'),
        ),
    ]
