# Generated by Django 2.2.6 on 2020-01-03 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20191114_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='status',
        ),
    ]
