# Generated by Django 2.2.6 on 2019-11-08 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name': 'Książka', 'verbose_name_plural': 'Książki'},
        ),
        migrations.AddField(
            model_name='books',
            name='owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='books',
            name='status',
            field=models.CharField(choices=[('AV', 'Available'), ('LO', 'On loan')], default='AV', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='books',
            unique_together={('title', 'author', 'owner')},
        ),
    ]
