# Generated by Django 2.2.6 on 2019-11-09 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_auto_20191108_2324'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Books',
        ),
    ]
