# Generated by Django 2.2.6 on 2019-11-10 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0004_loanbook'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loanbook',
            options={'verbose_name': 'Wypożyczone książki', 'verbose_name_plural': 'Wypożyczenia książek'},
        ),
    ]
